/* Copyright 2026 Starboard
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#pragma once

#define MATRIX_IO_DELAY 30

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_DISPLAY_128X32
#define OLED_TIMEOUT 60000

#define WS2812_DI_PIN GP2
#define RGBLIGHT_LED_COUNT 6
#define RGBLIGHT_LIMIT_VAL 128
#define RGBLIGHT_DEFAULT_VAL 64
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_DEFAULT_HUE 170
